---
- name: Install Google Chrome repository
  yum_repository:
    name: google-chrome
    description: Google Chrome Repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
  tags: applications

- name: Install Google Chrome
  dnf:
    name: google-chrome-stable
    state: present
  tags: applications